// <auto-generated />
using EaproERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EaproERP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221125333_SeedFactoryData")]
    partial class SeedFactoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EaproERP.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualTurnover")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsServiceCenter")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualTurnover = 12000000m,
                            BusinessName = "North Solar Hub",
                            ContactPerson = "Vikas Gupta",
                            IsServiceCenter = true,
                            Region = "North",
                            Tier = "Platinum"
                        },
                        new
                        {
                            Id = 2,
                            AnnualTurnover = 8500000m,
                            BusinessName = "Southern Energy Solutions",
                            ContactPerson = "S. Rajesh",
                            IsServiceCenter = false,
                            Region = "South",
                            Tier = "Gold"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIPerformanceInsight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AIPerformanceInsight = "",
                            BaseSalary = 45000m,
                            Bonus = 5000m,
                            Department = "Manufacturing",
                            Designation = "Plant Supervisor",
                            Name = "Amit Sharma"
                        },
                        new
                        {
                            Id = 102,
                            AIPerformanceInsight = "",
                            BaseSalary = 85000m,
                            Bonus = 18000m,
                            Department = "R&D",
                            Designation = "DSP Solar Engineer",
                            Name = "Priya Singh"
                        },
                        new
                        {
                            Id = 103,
                            AIPerformanceInsight = "",
                            BaseSalary = 38000m,
                            Bonus = 2000m,
                            Department = "Installation",
                            Designation = "PV Technician",
                            Name = "Ravi Verma"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIStockPrediction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO TRON-3200 3000VA 24V AI-MPPT Dual Battery PCU",
                            Price = 19349m,
                            StockLevel = 45
                        },
                        new
                        {
                            Id = 2,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO 3500VA 48V MPPT Single Phase Pure Sine Wave",
                            Price = 31570m,
                            StockLevel = 18
                        },
                        new
                        {
                            Id = 3,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO 5625VA 48V MPPT Solar Inverter",
                            Price = 51659m,
                            StockLevel = 8
                        },
                        new
                        {
                            Id = 4,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO 11 kW Three-Phase On-Grid Inverter",
                            Price = 85000m,
                            StockLevel = 5
                        },
                        new
                        {
                            Id = 5,
                            AIStockPrediction = "",
                            Category = "Solar Panel",
                            Name = "EAPRO 590W TOPCon Bifacial Solar Panel",
                            Price = 18500m,
                            StockLevel = 120
                        },
                        new
                        {
                            Id = 6,
                            AIStockPrediction = "",
                            Category = "Solar Panel",
                            Name = "EAPRO 550W Mono Half-Cut Solar Panel",
                            Price = 15000m,
                            StockLevel = 340
                        },
                        new
                        {
                            Id = 7,
                            AIStockPrediction = "",
                            Category = "Solar Panel",
                            Name = "EAPRO 445W Mono PERC Solar Panel",
                            Price = 12500m,
                            StockLevel = 85
                        },
                        new
                        {
                            Id = 8,
                            AIStockPrediction = "",
                            Category = "Solar Panel",
                            Name = "EAPRO 170W Polycrystalline Solar Panel",
                            Price = 4500m,
                            StockLevel = 15
                        },
                        new
                        {
                            Id = 9,
                            AIStockPrediction = "",
                            Category = "Battery",
                            Name = "EAPRO Enerbatt 250Ah Solar Battery",
                            Price = 16500m,
                            StockLevel = 60
                        },
                        new
                        {
                            Id = 10,
                            AIStockPrediction = "",
                            Category = "Battery",
                            Name = "EAPRO Hybrid Solar Tubular Battery 150Ah",
                            Price = 11000m,
                            StockLevel = 110
                        });
                });

            modelBuilder.Entity("EaproERP.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyTarget")
                        .HasColumnType("int");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitsCompleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentProduct = "TRON-3200 AI-MPPT",
                            DailyTarget = 250,
                            LineName = "Line Alpha-1",
                            QualityScore = 99.5m,
                            Status = "Active",
                            UnitsCompleted = 180
                        },
                        new
                        {
                            Id = 2,
                            CurrentProduct = "590W TOPCon Bifacial",
                            DailyTarget = 500,
                            LineName = "Line Beta-Sigma",
                            QualityScore = 98.8m,
                            Status = "Active",
                            UnitsCompleted = 410
                        },
                        new
                        {
                            Id = 3,
                            CurrentProduct = "Enerbatt 250Ah Tubular",
                            DailyTarget = 150,
                            LineName = "Line Gamma-Storage",
                            QualityScore = 92.4m,
                            Status = "Maintenance",
                            UnitsCompleted = 45
                        },
                        new
                        {
                            Id = 4,
                            CurrentProduct = "11kW On-Grid Inverter",
                            DailyTarget = 100,
                            LineName = "Line Delta-Grid",
                            QualityScore = 100.0m,
                            Status = "Active",
                            UnitsCompleted = 100
                        },
                        new
                        {
                            Id = 5,
                            CurrentProduct = "Core DSP Motherboards",
                            DailyTarget = 1200,
                            LineName = "Line Epsilon-PCB",
                            QualityScore = 99.9m,
                            Status = "Active",
                            UnitsCompleted = 850
                        },
                        new
                        {
                            Id = 6,
                            CurrentProduct = "5kW Hybrid PCU",
                            DailyTarget = 120,
                            LineName = "Line Zeta-Hybrid",
                            QualityScore = 100.0m,
                            Status = "Offline",
                            UnitsCompleted = 0
                        },
                        new
                        {
                            Id = 7,
                            CurrentProduct = "Prototype Smart-Grid Unit",
                            DailyTarget = 10,
                            LineName = "Line Omega-R&D",
                            QualityScore = 88.5m,
                            Status = "Active",
                            UnitsCompleted = 3
                        });
                });

            modelBuilder.Entity("EaproERP.Models.SolarProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityKW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SolarProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityKW = 150m,
                            ClientName = "Roorkee Industrial Complex",
                            ContractValue = 4500000m,
                            Location = "Roorkee",
                            ProjectType = "On-Grid",
                            Status = "Commissioned"
                        },
                        new
                        {
                            Id = 2,
                            CapacityKW = 50m,
                            ClientName = "Delhi Green Housing",
                            ContractValue = 1800000m,
                            Location = "Delhi",
                            ProjectType = "Hybrid",
                            Status = "Installation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
