// <auto-generated />
using System;
using EaproERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EaproERP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222073318_AddRecruitmentModule")]
    partial class AddRecruitmentModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EaproERP.Models.AmcNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NextScheduledService")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AmcContracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Pacific Mall Dehradun",
                            ContractExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractValue = 120000m,
                            NextScheduledService = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectSite = "Main Roof B",
                            ServiceFrequency = "Quarterly"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("PunchInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("PunchOutTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("EaproERP.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("EaproERP.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualTurnover")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsServiceCenter")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualTurnover = 12500000m,
                            BusinessName = "North Solar Hub Meerut",
                            ContactPerson = "Vikas Gupta",
                            IsServiceCenter = true,
                            Region = "North",
                            Tier = "Platinum"
                        },
                        new
                        {
                            Id = 2,
                            AnnualTurnover = 8500000m,
                            BusinessName = "Roorkee Energy Solutions",
                            ContactPerson = "Anil Tyagi",
                            IsServiceCenter = true,
                            Region = "North",
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 3,
                            AnnualTurnover = 25000000m,
                            BusinessName = "Delhi Solar Power Systems",
                            ContactPerson = "Sandeep Malhotra",
                            IsServiceCenter = false,
                            Region = "North",
                            Tier = "Platinum"
                        },
                        new
                        {
                            Id = 4,
                            AnnualTurnover = 4500000m,
                            BusinessName = "Southern Energy Chennai",
                            ContactPerson = "K. Ramakrishnan",
                            IsServiceCenter = true,
                            Region = "South",
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 5,
                            AnnualTurnover = 9800000m,
                            BusinessName = "Western Solar Pune",
                            ContactPerson = "Rahul Deshmukh",
                            IsServiceCenter = false,
                            Region = "West",
                            Tier = "Gold"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIPerformanceInsight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("BiometricCredentialId")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("BiometricPublicKey")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal?>("Bonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            BankAccountNumber = "",
                            BaseSalary = 45000m,
                            Bonus = 5000m,
                            DateOfJoining = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Manufacturing",
                            Designation = "Plant Supervisor",
                            Email = "amit.sharma@eapro.in",
                            EmergencyContact = "",
                            EmployeeCode = "EAP-2301-1001",
                            GovernmentId = "ABCDE1234F",
                            IFSCCode = "",
                            JobLocation = "Roorkee",
                            Name = "Amit Sharma",
                            Phone = "+91-9876543210"
                        },
                        new
                        {
                            Id = 102,
                            BankAccountNumber = "",
                            BaseSalary = 85000m,
                            Bonus = 18000m,
                            DateOfJoining = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "R&D",
                            Designation = "DSP Solar Engineer",
                            Email = "priya.singh@eapro.in",
                            EmergencyContact = "",
                            EmployeeCode = "EAP-2305-1002",
                            GovernmentId = "456789012345",
                            IFSCCode = "",
                            JobLocation = "Roorkee",
                            Name = "Priya Singh",
                            Phone = "+91-8765432109"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerGSTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGstInvoice")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EaproERP.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIStockPrediction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO TRON-3200 3000VA 24V AI-MPPT Dual Battery PCU",
                            Price = 19349m,
                            StockLevel = 45
                        },
                        new
                        {
                            Id = 2,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO 3500VA 48V MPPT Single Phase Pure Sine Wave",
                            Price = 31570m,
                            StockLevel = 18
                        },
                        new
                        {
                            Id = 5,
                            AIStockPrediction = "",
                            Category = "Solar Panel",
                            Name = "EAPRO 590W TOPCon Bifacial Solar Panel",
                            Price = 18500m,
                            StockLevel = 120
                        },
                        new
                        {
                            Id = 9,
                            AIStockPrediction = "",
                            Category = "Battery",
                            Name = "EAPRO Enerbatt 250Ah Solar Battery",
                            Price = 16500m,
                            StockLevel = 60
                        });
                });

            modelBuilder.Entity("EaproERP.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyTarget")
                        .HasColumnType("int");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitsCompleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentProduct = "TRON-3200 AI-MPPT",
                            DailyTarget = 250,
                            LineName = "Line Alpha-1",
                            QualityScore = 99.5m,
                            Status = "Active",
                            UnitsCompleted = 180
                        },
                        new
                        {
                            Id = 2,
                            CurrentProduct = "590W TOPCon Bifacial",
                            DailyTarget = 500,
                            LineName = "Line Beta-Sigma",
                            QualityScore = 98.8m,
                            Status = "Active",
                            UnitsCompleted = 410
                        });
                });

            modelBuilder.Entity("EaproERP.Models.ProjectEngine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommencementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionProgress")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoofType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShadowAnalysisScore")
                        .HasColumnType("int");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SystemCapacityKW")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProjectEngines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "UP Health Dept",
                            CommencementDate = new DateTime(2026, 2, 22, 13, 3, 17, 667, DateTimeKind.Local).AddTicks(1340),
                            ContractValue = 12500000m,
                            CurrentPhase = "Installation",
                            ExecutionProgress = 65,
                            ProjectName = "Roorkee Medical College Solar Hub",
                            ProjectType = "On-Grid",
                            RoofType = "RRC Slab",
                            ShadowAnalysisScore = 0,
                            SiteLocation = "Roorkee, UK",
                            SystemCapacityKW = 450.0
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "Smart City Auth",
                            CommencementDate = new DateTime(2026, 2, 22, 13, 3, 17, 667, DateTimeKind.Local).AddTicks(2490),
                            ContractValue = 4200000m,
                            CurrentPhase = "Site Survey",
                            ExecutionProgress = 15,
                            ProjectName = "Meerut IT Park Unit 4",
                            ProjectType = "Hybrid",
                            RoofType = "RRC Slab",
                            ShadowAnalysisScore = 0,
                            SiteLocation = "Meerut, UP",
                            SystemCapacityKW = 120.5
                        });
                });

            modelBuilder.Entity("EaproERP.Models.SalaryDisbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DaysPresent")
                        .HasColumnType("int");

                    b.Property<DateTime>("DisbursedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetPayout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWorkingDays")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryDisbursements");
                });

            modelBuilder.Entity("EaproERP.Models.SolarProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityKW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SolarProjects");
                });

            modelBuilder.Entity("EaproERP.Models.TrustBlock", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Index"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Index");

                    b.ToTable("TrustLedger");

                    b.HasData(
                        new
                        {
                            Index = 1,
                            Data = "GENESIS: Manufacturing Started (Roorkee Unit 4)",
                            Hash = "816E2247E11695CBA365930039E1C2E1",
                            PreviousHash = "0",
                            ProductId = "TRON-3200-S04-001",
                            Timestamp = new DateTime(2026, 2, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Index = 2,
                            Data = "QC Passed: Pure Sine Wave Efficiency 98.5%",
                            Hash = "2C8C3886A26B5061B465228D7017A44F",
                            PreviousHash = "816E2247E11695CBA365930039E1C2E1",
                            ProductId = "TRON-3200-S04-001",
                            Timestamp = new DateTime(2026, 2, 20, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CompanyName = "Silicon Tech Japan",
                            ContactPerson = "Kenji Sato",
                            Email = "sato@silicontech.jp",
                            OutstandingBalance = 4500000m,
                            ReliabilityScore = 98,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Logistics",
                            CompanyName = "Delta Logistics Meerut",
                            ContactPerson = "Vikas Tyagi",
                            Email = "v.tyagi@deltalog.in",
                            OutstandingBalance = 125000m,
                            ReliabilityScore = 85,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.WarrantyNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarrantyPeriodMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Anuj Dhiman",
                            IsRegistered = true,
                            ProductName = "Tron 3200 PCU",
                            PurchaseDate = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "TRON-3200-S04-001",
                            WarrantyPeriodMonths = 24
                        });
                });

            modelBuilder.Entity("EaproERP.Models.AttendanceRecord", b =>
                {
                    b.HasOne("EaproERP.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EaproERP.Models.SalaryDisbursement", b =>
                {
                    b.HasOne("EaproERP.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
