// <auto-generated />
using System;
using EaproERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EaproERP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907125619_PostgresInitialSetup")]
    partial class PostgresInitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EaproERP.Models.AmcNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ContractExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("NextScheduledService")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AmcContracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Pacific Mall Dehradun",
                            ContractExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ContractStartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ContractValue = 120000m,
                            NextScheduledService = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectSite = "Main Roof B",
                            ServiceFrequency = "Quarterly"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("PunchInTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("PunchOutTime")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("EaproERP.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliedDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStep = 1,
                            Email = "rahul.v@gmail.com",
                            Name = "Rahul Verma",
                            Position = "GenAI Developer",
                            ResumeUrl = "",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            AppliedDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStep = 3,
                            Email = "sneha.k@eapro.in",
                            Name = "Sneha Kapoor",
                            Position = "Supply Chain Manager",
                            ResumeUrl = "",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            AppliedDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStep = 4,
                            Email = "aditya.v@outlook.com",
                            Name = "Vikram Aditya",
                            Position = "Embedded Systems Engineer",
                            ResumeUrl = "",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            AppliedDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStep = 5,
                            Email = "pooja.h@gmail.com",
                            Name = "Pooja Hegde",
                            Position = "Technical Sales Executive",
                            ResumeUrl = "",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.CustomerTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductSerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CustomerTickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Rakesh Tiwari",
                            Description = "Inverter is showing error code E-04 during power cut.",
                            Email = "rakesh.t@gmail.com",
                            PhoneNumber = "+91-9876512345",
                            ProductSerialNumber = "TRON-3200-S04-005",
                            RequestType = "Complaint",
                            Status = "Open"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 18, 14, 15, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Meera Joshi",
                            Description = "Need installation for 5KW solar panels at my residence in Dehradun.",
                            Email = "meera.j@yahoo.com",
                            PhoneNumber = "+91-8765423456",
                            ProductSerialNumber = "EAPRO-590W-PANEL-SET",
                            RequestType = "Installation",
                            Status = "Resolved"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 21, 9, 45, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Suresh Kumar",
                            Description = "Registering newly purchased battery for standard 5-year warranty.",
                            Email = "suresh.k@outlook.com",
                            PhoneNumber = "+91-7654334567",
                            ProductSerialNumber = "ENERBATT-250AH-001",
                            RequestType = "Product Registration",
                            Status = "Open"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualTurnover")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsServiceCenter")
                        .HasColumnType("boolean");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualTurnover = 12500000m,
                            BusinessName = "North Solar Hub Meerut",
                            ContactPerson = "Vikas Gupta",
                            IsServiceCenter = true,
                            Region = "North",
                            Tier = "Platinum"
                        },
                        new
                        {
                            Id = 2,
                            AnnualTurnover = 8500000m,
                            BusinessName = "Roorkee Energy Solutions",
                            ContactPerson = "Anil Tyagi",
                            IsServiceCenter = true,
                            Region = "North",
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 3,
                            AnnualTurnover = 25000000m,
                            BusinessName = "Delhi Solar Power Systems",
                            ContactPerson = "Sandeep Malhotra",
                            IsServiceCenter = false,
                            Region = "North",
                            Tier = "Platinum"
                        },
                        new
                        {
                            Id = 4,
                            AnnualTurnover = 4500000m,
                            BusinessName = "Southern Energy Chennai",
                            ContactPerson = "K. Ramakrishnan",
                            IsServiceCenter = true,
                            Region = "South",
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 5,
                            AnnualTurnover = 9800000m,
                            BusinessName = "Western Solar Pune",
                            ContactPerson = "Rahul Deshmukh",
                            IsServiceCenter = false,
                            Region = "West",
                            Tier = "Gold"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AIPerformanceInsight")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte[]>("BiometricCredentialId")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("BiometricPublicKey")
                        .HasColumnType("bytea");

                    b.Property<decimal?>("Bonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GovernmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            BankAccountNumber = "",
                            BaseSalary = 45000m,
                            Bonus = 5000m,
                            DateOfJoining = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Manufacturing",
                            Designation = "Plant Supervisor",
                            Email = "amit.sharma@eapro.in",
                            EmergencyContact = "",
                            EmployeeCode = "EAP-2301-1001",
                            GovernmentId = "ABCDE1234F",
                            IFSCCode = "",
                            JobLocation = "Roorkee",
                            Name = "Amit Sharma",
                            Phone = "+91-9876543210"
                        },
                        new
                        {
                            Id = 102,
                            BankAccountNumber = "",
                            BaseSalary = 85000m,
                            Bonus = 18000m,
                            DateOfJoining = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "R&D",
                            Designation = "DSP Solar Engineer",
                            Email = "priya.singh@eapro.in",
                            EmergencyContact = "",
                            EmployeeCode = "EAP-2305-1002",
                            GovernmentId = "456789012345",
                            IFSCCode = "",
                            JobLocation = "Roorkee",
                            Name = "Priya Singh",
                            Phone = "+91-8765432109"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerGSTIN")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsGstInvoice")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EaproERP.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AIStockPrediction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO TRON-3200 3000VA 24V AI-MPPT Dual Battery PCU",
                            Price = 19349m,
                            StockLevel = 45
                        },
                        new
                        {
                            Id = 2,
                            AIStockPrediction = "",
                            Category = "Inverter",
                            Name = "EAPRO 3500VA 48V MPPT Single Phase Pure Sine Wave",
                            Price = 31570m,
                            StockLevel = 18
                        },
                        new
                        {
                            Id = 5,
                            AIStockPrediction = "",
                            Category = "Solar Panel",
                            Name = "EAPRO 590W TOPCon Bifacial Solar Panel",
                            Price = 18500m,
                            StockLevel = 120
                        },
                        new
                        {
                            Id = 9,
                            AIStockPrediction = "",
                            Category = "Battery",
                            Name = "EAPRO Enerbatt 250Ah Solar Battery",
                            Price = 16500m,
                            StockLevel = 60
                        });
                });

            modelBuilder.Entity("EaproERP.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DailyTarget")
                        .HasColumnType("integer");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitsCompleted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProductionLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentProduct = "TRON-3200 AI-MPPT",
                            DailyTarget = 250,
                            LineName = "Line Alpha-1",
                            QualityScore = 99.5m,
                            Status = "Active",
                            UnitsCompleted = 180
                        },
                        new
                        {
                            Id = 2,
                            CurrentProduct = "590W TOPCon Bifacial",
                            DailyTarget = 500,
                            LineName = "Line Beta-Sigma",
                            QualityScore = 98.8m,
                            Status = "Active",
                            UnitsCompleted = 410
                        });
                });

            modelBuilder.Entity("EaproERP.Models.ProjectEngine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CommencementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExecutionProgress")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoofType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShadowAnalysisScore")
                        .HasColumnType("integer");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SystemCapacityKW")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ProjectEngines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "UP Health Dept",
                            CommencementDate = new DateTime(2026, 9, 7, 18, 26, 18, 618, DateTimeKind.Local).AddTicks(50),
                            ContractValue = 12500000m,
                            CurrentPhase = "Installation",
                            ExecutionProgress = 65,
                            ProjectName = "Roorkee Medical College Solar Hub",
                            ProjectType = "On-Grid",
                            RoofType = "RRC Slab",
                            ShadowAnalysisScore = 0,
                            SiteLocation = "Roorkee, UK",
                            SystemCapacityKW = 450.0
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "Smart City Auth",
                            CommencementDate = new DateTime(2026, 9, 7, 18, 26, 18, 618, DateTimeKind.Local).AddTicks(1200),
                            ContractValue = 4200000m,
                            CurrentPhase = "Site Survey",
                            ExecutionProgress = 15,
                            ProjectName = "Meerut IT Park Unit 4",
                            ProjectType = "Hybrid",
                            RoofType = "RRC Slab",
                            ShadowAnalysisScore = 0,
                            SiteLocation = "Meerut, UP",
                            SystemCapacityKW = 120.5
                        });
                });

            modelBuilder.Entity("EaproERP.Models.SalaryDisbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DaysPresent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DisbursedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NetPayout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWorkingDays")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryDisbursements");
                });

            modelBuilder.Entity("EaproERP.Models.SolarProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityKW")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SolarProjects");
                });

            modelBuilder.Entity("EaproERP.Models.StoreLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DealerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StoreLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sarojini Nagar, Amausi",
                            City = "Lucknow",
                            ContactPerson = "Srikant Dubey",
                            DealerName = "GENSTAR AGROVET FARMS",
                            Mobile = "9935200038",
                            Pincode = "226008",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 2,
                            Address = "No 8 Tholkappiyar street Arcot, Anna silai",
                            City = "Vellore",
                            ContactPerson = "Thanigai Malai",
                            DealerName = "Power tech Electronics",
                            Mobile = "9789586737",
                            Pincode = "632503",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 3,
                            Address = "7, BRINDHA GARDEN, SASTRY NAGAR, VAIKKAMEDU",
                            City = "Erode",
                            ContactPerson = "KARTHIGAIVENI",
                            DealerName = "Inspire Energy care",
                            Mobile = "9940652303",
                            Pincode = "638002",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4/5, POOTTAI MAIN ROAD",
                            City = "Kallakkurichi",
                            ContactPerson = "PERUMAL SATHEESH KUMAR",
                            DealerName = "STAR ELECTRICAL",
                            Mobile = "9698903550",
                            Pincode = "606401",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 5,
                            Address = "NO 15, WARRIOR HOUSE, BHARATHIDASAN STREET, TEACHERS COLONY",
                            City = "Erode",
                            ContactPerson = "MR.P.SRINIVASAN",
                            DealerName = "WARRIOR POWER SYSTEM S",
                            Mobile = "7200281000",
                            Pincode = "638011",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 6,
                            Address = "121 othavada Street kodapakkm, Avm",
                            City = "Chennai",
                            ContactPerson = "Thomas",
                            DealerName = "VINT ENTERPRISES",
                            Mobile = "8807191615",
                            Pincode = "600024",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Konnur high road, 5th St, railway quarters, Ayanavaram",
                            City = "Chennai",
                            ContactPerson = "Mr. ganesh kumar",
                            DealerName = "Thirumal Enterprises",
                            Mobile = "9840191279",
                            Pincode = "600023",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 8,
                            Address = "BUILDING NO. 17, 1ST MAIN STREET, MVM NAGAR",
                            City = "Dindigul",
                            ContactPerson = "MR. PARTHASARATHI PERUMAL KANNIAPPAN",
                            DealerName = "TED VAAA GLOBAL ENTERPRISE",
                            Mobile = "9442233383",
                            Pincode = "624004",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Joseph convent complex, opp Joseph convent",
                            City = "Kanyakumari",
                            ContactPerson = "GEORGEMARIAARPUTHAM GEORGEFERNANDO",
                            DealerName = "SUN TRADERS",
                            Mobile = "8122434145",
                            Pincode = "629001",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 10,
                            Address = "S.F. NO. 308/1B1A, NITHYA, TIRUCHENGODE ROAD, PALLIPALAYAM",
                            City = "Namakkal",
                            ContactPerson = "NITHYA GURUMOORTHY",
                            DealerName = "SSM BATTERIES",
                            Mobile = "9865884748",
                            Pincode = "638006",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 11,
                            Address = "no 14 konar street jaihindpuram",
                            City = "Madurai",
                            ContactPerson = "MR. SELVAPRAKASH MURUGESAN",
                            DealerName = "PRAKASH GREEN ENERGY",
                            Mobile = "9994901500",
                            Pincode = "625011",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 12,
                            Address = "no-1 9 th Lane 1 St cross street Adayar, sastri nagar",
                            City = "Chennai",
                            ContactPerson = "Jagathes",
                            DealerName = "POWER HOUSE",
                            Mobile = "9962869007",
                            Pincode = "620020",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 13,
                            Address = "NO 1/105, 52ND STREET, 7TH AVENUE, ASHOK NAGAR",
                            City = "Chennai",
                            ContactPerson = "SUBHASHREE",
                            DealerName = "OMEGA DIGITAL SYSTEMS",
                            Mobile = "9667891576",
                            Pincode = "600083",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 14,
                            Address = "3/188-A, MAIN ROAD, POOLANGULAM, ALANGULAM",
                            City = "Tirunelveli",
                            ContactPerson = "R MUTHUSELVI",
                            DealerName = "MSM TAMIL TRADERS",
                            Mobile = "6369922811",
                            Pincode = "627415",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 15,
                            Address = "395/1A1, CHENNAI BYE PASS HIGH WAY CIRCLE, NEAR SBI ATM",
                            City = "Krishnagiri",
                            ContactPerson = "KARIYAPPA SIDDANNAN VEERABADRAN",
                            DealerName = "MICRO BATTERY HOUSE",
                            Mobile = "9943905073",
                            Pincode = "635001",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 16,
                            Address = "PLOT NO 23, VEERAIYA STREET, KUNDUPALAYAM, THATTANCHAVADY",
                            City = "Pondicherry",
                            ContactPerson = "SELVA KUMAR",
                            DealerName = "LIGHTNING POWER CONTROL",
                            Mobile = "9843438701",
                            Pincode = "605009",
                            State = "Puducherry"
                        },
                        new
                        {
                            Id = 17,
                            Address = "WARD -1 D/NO-60N3, CHINNAMANUR MAIN ROAD, THEVARAM",
                            City = "Theni",
                            ContactPerson = "JEYA PRINCILA MARY",
                            DealerName = "JEYAS SOLAR AND POWER SERVICE",
                            Mobile = "8778900700",
                            Pincode = "625530",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 18,
                            Address = "PLOT NO 1&2 KAVIMANI STREET, BYE PASS RAAD, NEHRU NAGAR",
                            City = "Madurai",
                            ContactPerson = "SAMBATHRAJAN",
                            DealerName = "GASTON PLANTE POWER CORPORATION",
                            Mobile = "9843871710",
                            Pincode = "625016",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 19,
                            Address = "G NEXT ENERGIES, THIRUVAMATHUR ROAD, VILLUPURAM BYE PASS ROAD",
                            City = "Viluppuram",
                            ContactPerson = "J MOHAMMED RIAZ JAFARULLAH",
                            DealerName = "G- NEXTER ENERGIES",
                            Mobile = "9994190901",
                            Pincode = "605602",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 20,
                            Address = "3/177, DEVAMPALAYAM, PALANGARAI, AVANASHI",
                            City = "Tirupur",
                            ContactPerson = "P. NALLASIVAM",
                            DealerName = "FINETECH SYSTEMS",
                            Mobile = "9842273559",
                            Pincode = "641654",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 21,
                            Address = "256 KAMARAJ NAGAR COLONY",
                            City = "Salem",
                            ContactPerson = "JAGANATHAN PADMANABHAN",
                            DealerName = "DELTA SYSTEMS",
                            Mobile = "9443203324",
                            Pincode = "636014",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 22,
                            Address = "PWGR+QP7, Achalpur - Ganjdudwara Rd",
                            City = "Kasganj",
                            ContactPerson = "Atul Gupta",
                            DealerName = "Dev Electrical Ganjdundwara",
                            Mobile = "9720411499",
                            Pincode = "207242",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 23,
                            Address = "A-578, Hapur Rd, Jawahar Gang, Lothi Gate Nagar, Ganga Nagar Colony",
                            City = "Hapur",
                            ContactPerson = "Mohit Agarwal",
                            DealerName = "Singhal Distributor",
                            Mobile = "9837170344",
                            Pincode = "245101",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 24,
                            Address = "behror",
                            City = "Alwar",
                            ContactPerson = "TEJPAL SINGH",
                            DealerName = "Naveen electric",
                            Mobile = "9462505158",
                            Pincode = "301701",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 25,
                            Address = "manoharpur",
                            City = "Churu",
                            ContactPerson = "Ajit singh",
                            DealerName = "Shree Shayam enterprises",
                            Mobile = "9799278745",
                            Pincode = "303103",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 26,
                            Address = "BERI, ON GROUND, JHAJHAR ROAD",
                            City = "Sikar",
                            ContactPerson = "SHAKTI SINGH KHINCHI",
                            DealerName = "Maa Karni enterprises",
                            Mobile = "8764165732",
                            Pincode = "332031",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 27,
                            Address = "68 A, NEW DHAN MANDI",
                            City = "Hanumangarh",
                            ContactPerson = "Davinder Garg",
                            DealerName = "parveen Kumar and company",
                            Mobile = "9530001174",
                            Pincode = "335513",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 28,
                            Address = "21 - NEW DHAN MANDI CHHOTI",
                            City = "Shre Ganga Nagar",
                            ContactPerson = "GURTEJ KATARIA",
                            DealerName = "Suntech power system",
                            Mobile = "9314408934",
                            Pincode = "335001",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Sankhla Electric Store, Opp. Roadways Bustand",
                            City = "Nagaur",
                            ContactPerson = "Premraj Sankhla",
                            DealerName = "Sankhla electric store",
                            Mobile = "9928044300",
                            Pincode = "341001",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 30,
                            Address = "P.NO.19, MITRA VIHAR-C, JATO KI DHANI, GAJSINGHPURA, VAISHALI NAGAR",
                            City = "Jaipur",
                            ContactPerson = "Sanjay Kumawat",
                            DealerName = "Roxis infra power energy pvt.Ltd",
                            Mobile = "9214031462",
                            Pincode = "302021",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 31,
                            Address = "moradabad",
                            City = "Moradabad",
                            ContactPerson = "Naeem",
                            DealerName = "is solar",
                            Mobile = "9837793032",
                            Pincode = "244001",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 32,
                            Address = "KHADAKPUR DEVIPURA, VAISHALI COLONY, BAZPUR ROAD",
                            City = "Kashipur",
                            ContactPerson = "MANJU RAWAT",
                            DealerName = "Heliacal Urja",
                            Mobile = "9837211548",
                            Pincode = "244713",
                            State = "Uttarakhand"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Ayub Khan Choraha",
                            City = "Bareilly",
                            ContactPerson = "Jasoria Marketvers",
                            DealerName = "Jasoria Marketvers",
                            Mobile = "7830000313",
                            Pincode = "243001",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 34,
                            Address = "38, ADARSH COLONY, CIVIL LINES RAMPUR",
                            City = "Rampur",
                            ContactPerson = "DEVANK JUNEJA",
                            DealerName = "Pearl Enterprises",
                            Mobile = "9758200022",
                            Pincode = "244901",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 35,
                            Address = "CHANDAUSI RAOD",
                            City = "Sambhal",
                            ContactPerson = "rafik",
                            DealerName = "M.R. Battery Services",
                            Mobile = "9837537498",
                            Pincode = "244302",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 36,
                            Address = "VILL MAKSOODPUR NAWADA NEAR GALAXY APARTMENT JOYA ROAD AMROHA",
                            City = "Amroha",
                            ContactPerson = "Deepak",
                            DealerName = "Goel Enterprises",
                            Mobile = "7017726416",
                            Pincode = "244221",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Mota Aam, Shakoor Nagar, Najibabad",
                            City = "Bijnor",
                            ContactPerson = "PARDEEP KUMAR",
                            DealerName = "Mama Trading Company",
                            Mobile = "9927764041",
                            Pincode = "246763",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 38,
                            Address = "KHATAULI COLD STORE, BUDHANA ROAD, NEAR SISHU SHIKSHA NIKETAN SCHOOL",
                            City = "Muzaffarnagar",
                            ContactPerson = "MOHD HUZAIF",
                            DealerName = "Bharat Power Corporation",
                            Mobile = "9259536731",
                            Pincode = "251201",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 39,
                            Address = "18 C, MANGAL NAGAR, NEAR POST OFFICE, NAWAB GANJ",
                            City = "Saharanpur",
                            ContactPerson = "HARSH KUMAR DAWAR",
                            DealerName = "Ritika Electronics",
                            Mobile = "9410223340",
                            Pincode = "247001",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 40,
                            Address = "GROUND FLOOR, SHOP NO 2, MORDERN SHOPING CENTER, AGRA ROAD, NEAR GANDHI PARK",
                            City = "Aligarh",
                            ContactPerson = "Bharat Kumar Gupta",
                            DealerName = "M/s Aligarh Power point",
                            Mobile = "9897198298",
                            Pincode = "202001",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 41,
                            Address = "A-76, SHRI RADHA PURAM, GANESHRA ROAD, NATIONAL HIGHWAY 19",
                            City = "Mathura",
                            ContactPerson = "Darpan",
                            DealerName = "Innomindset LLP",
                            Mobile = "9897509407",
                            Pincode = "281001",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Junction Road, Khurja",
                            City = "Bulandshahr",
                            ContactPerson = "Divyanshu Singhal",
                            DealerName = "Singhal Solar Traders",
                            Mobile = "9528938181",
                            Pincode = "203131",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 43,
                            Address = "NH-58, MEERUT DELHI BYPASS",
                            City = "Meerut",
                            ContactPerson = "Puneet Bansal",
                            DealerName = "Upasana Saur Urja Kendra",
                            Mobile = "8899280702",
                            Pincode = "250001",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 44,
                            Address = "KHASRA NO. 197, MAUJA CHAKHAFFTAM JOHRA BAGH, RAM BAGH",
                            City = "Agra",
                            ContactPerson = "Manoj chauhan",
                            DealerName = "Green Field Energy",
                            Mobile = "7500656543",
                            Pincode = "282006",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 45,
                            Address = "0, SHANTI KUNJ, 0, MURSAN GATE",
                            City = "Hathras",
                            ContactPerson = "Amit Bansal",
                            DealerName = "M/s Bansal Energy System",
                            Mobile = "9897545376",
                            Pincode = "204101",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 46,
                            Address = "718, GYANDEEP ROAD, KHERA MOHALLA",
                            City = "Firozabad",
                            ContactPerson = "Ram Kumar",
                            DealerName = "Radiant Solars",
                            Mobile = "8273529872",
                            Pincode = "283135",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 47,
                            Address = "593, NAI BASTI",
                            City = "Etah",
                            ContactPerson = "Usha Kumari",
                            DealerName = "M/s Mahadev Traders",
                            Mobile = "9870807461",
                            Pincode = "207001",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 48,
                            Address = "NATIONAL HIGHWAY ROAD, REVENUE MOUZA, DELINA BRANCH POST OFFICE, DILNA",
                            City = "Baramulla",
                            ContactPerson = "ISHFAQ AHMED",
                            DealerName = "KASHMIR VALLEY",
                            Mobile = "9966287328",
                            Pincode = "193201",
                            State = "Jammu & Kashmir"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Near Gopal Dev Chownk Rewari, Opp Ceat Shopee",
                            City = "Rewari",
                            ContactPerson = "Mr Moksh Yadav",
                            DealerName = "MAHADEV ENTERPRISES",
                            Mobile = "8685832677",
                            Pincode = "123401",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Near Escorts Metro Station",
                            City = "Faridabad",
                            ContactPerson = "Mr Sharan Jit Singh",
                            DealerName = "SWARN BATTERY",
                            Mobile = "9810801817",
                            Pincode = "121006",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Sondapur",
                            City = "Panipat",
                            ContactPerson = "Mr Anirudh",
                            DealerName = "SHREE BALAJI TRADERS",
                            Mobile = "9050707078",
                            Pincode = "132103",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 52,
                            Address = "SHOP NO. 5, NEAR RAILWAY STATION, KAWI ROAD",
                            City = "Panipat",
                            ContactPerson = "Mr Bijender",
                            DealerName = "MALIK TRADING COMPANY",
                            Mobile = "8607356000",
                            Pincode = "132113",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 53,
                            Address = "123 NARENDRA NAGAR RATHDANA ROAD NEAR SBI BANK",
                            City = "Sonipat",
                            ContactPerson = "Mr Amit Malik",
                            DealerName = "ADVANCE MODULAR TECHNOLOGY",
                            Mobile = "9466769467",
                            Pincode = "131001",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 54,
                            Address = "SHOP NO. -32, MAIN MARKET, SECTOR 14",
                            City = "Karnal",
                            ContactPerson = "Mr Madhukar",
                            DealerName = "SAT SOLAR ENERGY PRIVATE LIMITED",
                            Mobile = "7206606112",
                            Pincode = "132001",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 55,
                            Address = "SHOP NO 4, OPP MARUTI SHOWROOM G.T ROAD",
                            City = "Panipat",
                            ContactPerson = "Mr Virender CHUGH",
                            DealerName = "NISHAN AUTOMOBILES",
                            Mobile = "9896691205",
                            Pincode = "132103",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 56,
                            Address = "C/O SUBE SINGH 46 WARD NO 09 SATPOLI MOHALLA",
                            City = "Jhajjar",
                            ContactPerson = "Mr Hritik",
                            DealerName = "SHUBHAM BATTERY HOUSE",
                            Mobile = "8683864142",
                            Pincode = "124103",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 57,
                            Address = "40, Saini Colony, Jhansa Road",
                            City = "Kurukshetra",
                            ContactPerson = "Mr Vimal",
                            DealerName = "ISHAAN BRIGHT ENERGY",
                            Mobile = "9671202019",
                            Pincode = "136118",
                            State = "Haryana"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Delhi Rd, Asaf Nagar",
                            City = "Roorkee",
                            ContactPerson = "Vikas Tyagi",
                            DealerName = "Roorkee Solar Hub",
                            Mobile = "8650115000",
                            Pincode = "247666",
                            State = "Uttarakhand"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Phase 2, Hinjewadi IT Park",
                            City = "Pune",
                            ContactPerson = "Rahul Deshmukh",
                            DealerName = "Pune Energy Systems",
                            Mobile = "9823012345",
                            Pincode = "411057",
                            State = "Maharashtra"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.TrustBlock", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Index");

                    b.ToTable("TrustLedger");

                    b.HasData(
                        new
                        {
                            Index = 1,
                            Data = "GENESIS: Manufacturing Started (Roorkee Unit 4)",
                            Hash = "816E2247E11695CBA365930039E1C2E1",
                            PreviousHash = "0",
                            ProductId = "TRON-3200-S04-001",
                            Timestamp = new DateTime(2026, 2, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Index = 2,
                            Data = "QC Passed: Pure Sine Wave Efficiency 98.5%",
                            Hash = "2C8C3886A26B5061B465228D7017A44F",
                            PreviousHash = "816E2247E11695CBA365930039E1C2E1",
                            ProductId = "TRON-3200-S04-001",
                            Timestamp = new DateTime(2026, 2, 20, 14, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EaproERP.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CompanyName = "Silicon Tech Japan",
                            ContactPerson = "Kenji Sato",
                            Email = "sato@silicontech.jp",
                            OutstandingBalance = 4500000m,
                            ReliabilityScore = 98,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Logistics",
                            CompanyName = "Delta Logistics Meerut",
                            ContactPerson = "Vikas Tyagi",
                            Email = "v.tyagi@deltalog.in",
                            OutstandingBalance = 125000m,
                            ReliabilityScore = 85,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EaproERP.Models.WarrantyNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WarrantyPeriodMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Anuj Dhiman",
                            IsRegistered = true,
                            ProductName = "Tron 3200 PCU",
                            PurchaseDate = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            SerialNumber = "TRON-3200-S04-001",
                            WarrantyPeriodMonths = 24
                        });
                });

            modelBuilder.Entity("EaproERP.Models.AttendanceRecord", b =>
                {
                    b.HasOne("EaproERP.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EaproERP.Models.SalaryDisbursement", b =>
                {
                    b.HasOne("EaproERP.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
